import blockchain.Block;
import mobility.StaticPoint;
import mobility.RandomWalk;
import network.FastChannel;
import node.Node;
import simulators.SpreadSim;

import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

    public static void main(String[] args) {
        runTrustedNodesRangeTest();
    }

    public static void runTrustedNodesRangeTest() {
        double bw = 100000; // 100 KB/s
        double maxNodeBw = 1000000; // 1 MB/s
        for (int range = 10; range <= 100; range += 10) {
            System.out.print(range + ", ");
            ArrayList<Node> nodes = new ArrayList<Node>();
            // 100 nodes in our simulation
            int numNodes = 50;
            for (int i = 0; i < numNodes; i++) {
                RandomWalk m = new RandomWalk();
                for (int t = 0; t < 120; t++) {
                    m.model(1.0);
                }
                Node n = new Node(m, maxNodeBw, range);
                nodes.add(n);
            }

            // Create the simulation
            double simStep = 0.5; // 0.5 seconds
            SpreadSim sim = new SpreadSim(simStep, nodes, bw);

            // Run the simulation
            sim.run(3600); // Run the simulation for 1 hours
            System.out.println();
        }
    }
}
